= Mall API Guide
김준섭;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response
:docinfo: shared-head

[[overview]]
= 개요

== link:/docs/index.html[home]

[[overview-error-verbs]]
== 오류 코드

|===
| 발생 API | CAUSE | CODE | MESSAGE


|
|===

[[overview-api-grant]]
== API 권한

|===
| 사용 API | 필요 권한

| <<resources-story-create>>
| STORY

| <<resources-story-query>>
| STORY

| <<resources-stories-query>>
| STORY

| <<resources-story-update>>
| STORY

| <<resources-story-delete>>
| STORY

| <<resources-story-update-used>>
| STORY

| <<resources-story-update-unused>>
| STORY

|
|===

[[history]]
== 히스토리

히스토리는 문서의 변경이력을 표시한다.

- 2020-12-15

* 문서 생성

[[resources-story]]
== 쇼핑 스토리 리소스

쇼핑 스토리 리소스(admin)을 사용할 수 있습니다.

[[resources-story-create]]
=== 쇼핑 스토리 정보 생성

'POST' 요청을 사용해서 쇼핑 스토리 정보를 생성할 수 있다.

operation::create-story[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-stories-query]]
=== 쇼핑 스토리 조회

'GET' 요청을 사용해서 쇼핑 스토리 정보를 조회할 수 있다.

operation::query-stories[snippets='request-parameters,response-fields,curl-request,http-response']

[[resources-story-query]]
=== 쇼핑 스토리 단일 조회

'GET' 요청을 사용해서 쇼핑 스토리 단일 정보를 조회할 수 있다.

operation::query-story[snippets='response-fields,curl-request,http-response']

[[resources-story-update]]
=== 쇼핑 스토리 수정

'PUT' 요청을 사용해서 쇼핑 스토리 정보를 수정할 수 있다.

operation::update-story[snippets='path-parameters,request-fields,curl-request,http-response']

[[resources-story-delete]]
=== 쇼핑 스토리 삭제

'DELETE' 요청을 사용해서 쇼핑 스토리을 삭제할 수 있다.

operation::delete-story[snippets='path-parameters,curl-request,http-response']

[[resources-story-update-used]]
=== 쇼핑 스토리 사용 상태로 수정

'PUT' 요청을 사용해서 쇼핑 스토리를 사용 상태로 변경할 수 있다.

operation::update-story-used[snippets='path-parameters,curl-request,http-response']

[[resources-story-update-unused]]
=== 쇼핑 스토리 중지 상태로 수정

'PUT' 요청을 사용해서 쇼핑 스토리를 사용 중지상태로 변경할 수 있다.

operation::update-story-unused[snippets='path-parameters,curl-request,http-response']
