= Mall API Guide
김준섭;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response
:docinfo: shared-head

[[overview]]
= 개요

== link:/docs/index.html[home]

[[overview-error-verbs]]
== 오류 코드

|===
| 발생 API | CAUSE | CODE | MESSAGE


|
|===

[[overview-api-grant]]
== API 권한

|===
| 사용 API | 필요 권한

| <<resources-coupon-create>>
| COUPON

| <<resources-coupon-query>>
| COUPON

| <<resources-coupons-query>>
| COUPON

| <<resources-coupon-update>>
| COUPON

| <<resources-coupon-delete>>
| COUPON

| <<resources-coupon-update-used>>
| COUPON

| <<resources-coupon-update-unused>>
| COUPON

|
|===

[[hicoupon]]
== 히스토리

히스토리는 문서의 변경이력을 표시한다.

- 2020-12-16

* 문서 생성

[[resources-coupon]]
== 쿠폰 리소스

쿠폰 리소스(admin)을 사용할 수 있습니다.

[[resources-coupon-create]]
=== 쿠폰 정보 생성

'POST' 요청을 사용해서 쿠폰 정보를 생성할 수 있다.

operation::create-coupon[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-coupons-query]]
=== 쿠폰 조회

'GET' 요청을 사용해서 쿠폰 정보를 조회할 수 있다.

operation::query-coupons[snippets='request-parameters,response-fields,curl-request,http-response']

[[resources-coupon-query]]
=== 쿠폰 단일 조회

'GET' 요청을 사용해서 쿠폰 단일 정보를 조회할 수 있다.

operation::query-coupon[snippets='response-fields,curl-request,http-response']

[[resources-coupon-update]]
=== 쿠폰 수정

'PUT' 요청을 사용해서 쿠폰 정보를 수정할 수 있다.

operation::update-coupon[snippets='path-parameters,request-fields,curl-request,http-response']

[[resources-coupon-delete]]
=== 쿠폰 삭제

'DELETE' 요청을 사용해서 쿠폰을 삭제할 수 있다.

operation::delete-coupon[snippets='path-parameters,curl-request,http-response']

[[resources-coupon-update-used]]
=== 쿠폰 사용 상태로 수정

'PUT' 요청을 사용해서 쿠폰를 사용 상태로 변경할 수 있다.

operation::update-coupon-used[snippets='path-parameters,curl-request,http-response']

[[resources-coupon-update-unused]]
=== 쿠폰 사용 중지 상태로 수정

'PUT' 요청을 사용해서 쿠폰를 사용 중지 상태로 변경할 수 있다.

operation::update-coupon-unused[snippets='path-parameters,curl-request,http-response']
