= Mall API Guide
김준섭;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response
:docinfo: shared-head

[[overview]]
= 개요

== link:/docs/index.html[home]

[[overview-error-verbs]]
== 오류 코드

|===
| 발생 API | CAUSE | CODE | MESSAGE

| <<resources-member-update>>
| 입력한 비밀번호가 현재 비밀번호와 다를경우
| 4001
| 비밀번호 혹은 이메일을 확인해주세요.


| <<resources-member-create>>
| 이미 가입된 이메일로 회원가입
| 4008
| 이미 등록된 이메일 입니다.

| <<resources-member-create>>
| 이미 가입된 사번으로 회원가입
| 4009
| 이미 등록된 사번 입니다.

| <<resources-member-login>>
| 비밀번호가 맞지 않을 경우
| 4001
| 비밀번호 혹은 이메일을 확인해주세요.

| <<resources-member-login>>
| 회원 승인이 거절된 경우
| 4002
| 회원 승인이 거절되었습니다.

| <<resources-member-login>>
| 회원 승인이 요청중인 경우
| 4003
| 회원 승인 요청 처리중 입니다.

| <<resources-member-login>>
| 탈퇴한 회원일 경우
| 4004
| 탈퇴한 회원입니다.

| <<resources-member-login>>
| 입력한 이메일이 존재하지 않을 경우
| 4005
| 비밀번호 혹은 이메일을 확인해주세요.

| <<resources-member-refresh>>
| 입력한 리프레시 토큰에 해당하는 회원이 존재하지 않는경우
| 4006
| 요청한 리프레시 토큰으로 사용자를 찾을 수 없습니다.

| <<resources-member-refresh>>
| 입력한 리프레시 토큰이 만료된 경우
| 4007
| 만료된 리프레시 토큰입니다.

| <<resources-member-update-password>>
| 입력한 토큰으로 인증정보를 찾을 수 없는 경우
| 4013
| 인증에 실패하였습니다. 재 인증 후 시도해 주세요.

| <<resources-member-connect-social>>
| 이미 다른계정과 연동된 소셜 계정일 경우
| 4051
| 이미 가입된 소셜 회원입니다.


|
|===

[[history]]
== 히스토리

히스토리는 문서의 변경이력을 표시한다.
- 2021-01-27

* <<resources-member-update>> 추가

* <<resources-member-delete>> 추가

* <<resources-member-find-email>> 추가

* <<resources-member-update-password>> 수정

- 2020-10-30

* <<resources-member-query-current-ban>> 응답 파라미터 수정

- 2020-10-29

* <<resources-member-query-current-ban>> 최초 생성

* <<overview-error-verbs>> 추가

* <<resources-member-update-password>> 최초 생성

- 2020-10-28

* <<overview-error-verbs>> 추가 및 수정

* <<resources-member-refresh>> 최초 생성

* <<resources-member-query-current>> 최초 생성


- 2020-10-13

* <<overview-error-verbs>> 최초 생성

* <<resources-member-login>> 최초 생성

* <<resources-member-create>> 최초 생성

* 문서 생성

[[resources-member]]
== 회원 리소스 리스트

리소스를 사용할 수 있습니다.

[[resources-member-check-cert-email]]
=== 이메일 중복 검사

'POST' 요청을 사용해서 이메일 중복을 검사할 수 있다..

operation::create-check-email[snippets='request-fields,curl-request,http-response']

[[resources-member-join-phone-cert-key-create]]
=== 회원가입시 핸드폰번호 인증번호 발송

'POST' 요청을 사용해서 회원가입시 핸드폰번호 인증번호를 발송할 수 있다.

operation::create-member-join-phone-cert-key[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-join-cert-key-create]]
=== 핸드폰 번호 인증 체크 및 회원가입 토큰 발급

'POST' 요청을 사용해서 핸드폰 번호 인증 체크 및 회원가입 토큰을 발급받을 수 있다.

operation::create-member-join-cert-key[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-create]]
=== 회원 가입

'POST' 요청을 사용해서 회원가입을 진행할 수 있다.

operation::create-member-success[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-delete]]
=== 회원 탈퇴

'PUT' 요청을 사용해서 회원탈퇴를 할 수 있다.

operation::delete-member[snippets='request-fields,curl-request,http-response']

[[resources-member-update]]
=== 회원 수정

'PUT' 요청을 사용해서 회원을 수정 할 수 있다.

operation::update-member[snippets='request-fields,curl-request,http-response']

[[resources-member-connect-social]]
=== 회원 계정 연결

- 로그인 상태에서만 사용할 수 있음.

'POST' 요청을 사용해서 소셜 계정 연동을 진행할 수 있다.

operation::create-connection-social[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-login]]
=== 회원 로그인

'POST' 요청을 사용해서 토큰을 발급 받을 수 있다.

operation::create-login-token-success[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-refresh]]
=== 회원 토큰 재발급

'POST' 요청을 사용해서 토큰을 재발급 받을 수 있다.

operation::create-refresh-token-success[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-query-current]]
=== 회원 현재 정보 조회

'GET' 요청을 사용해서 현재 회원의 정보를 조회할 수 있다.

operation::query-member-current[snippets='response-fields,curl-request,http-response']

[[resources-member-query-current-ban]]
=== 회원 현재 이용 제한 사유 조회

'GET' 요청을 사용해서 현재 회원의 이용 제한 사유를 조회할 수 있다.

operation::query-member-current-ban-cause[snippets='response-fields,curl-request,http-response']

[[resources-member-email-phone-cert-key-create]]
=== 이메일 찾기 핸드폰 인증토큰 발급

'POST' 요청을 사용해서 이메일 찾기 핸드폰번호 인증번호를 발송할 수 있다.

operation::create-member-email-phone-cert-key[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-email-cert-key-create]]
=== 이메일 찾기 핸드폰 인증 체크 및 이메일 찾기 토큰 발급

'POST' 요청을 사용해서 이메일 찾기 핸드폰 번호 인증 체크 및 이메일 찾기 토큰을 발급받을 수 있다.

operation::create-member-email-cert-key[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-find-email]]
=== 회원 이메일 찾기

'POST' 요청을 사용해서 회원의 이메일을 찾을 수 있다.

<<resources-member-email-phone-cert-key-create>> 이 선행된다.

<<resources-member-email-cert-key-create>> 이 선행된다.

operation::create-find-email[snippets='request-fields,curl-request,http-response']

[[resources-member-password-phone-cert-key-create]]
=== 비밀번호 찾기 핸드폰번호 인증번호 발송

'POST' 요청을 사용해서 비밀번호 찾기 핸드폰번호 인증번호를 발송할 수 있다.

operation::create-member-password-phone-cert-key[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-password-cert-key-create]]
=== 비밀번호 찾기 핸드폰번호 인증 체크 및 비밀번호 찾기 토큰 발급

'POST' 요청을 사용해서 비밀번호 찾기 핸드폰 번호 인증 체크 및 비밀번호 찾기 토큰을 발급받을 수 있다.

operation::create-member-password-cert-key[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-member-update-password]]
=== 회원 비밀번호 변경

'PUT' 요청을 사용해서 회원의 비밀번호를 변경할 수 있다.

<<resources-member-password-phone-cert-key-create>> 이 선행된다.

<<resources-member-password-cert-key-create>> 이 선행된다.

operation::update-member-password[snippets='request-fields,curl-request,http-response']